---
# Collections are installed from collections/requirements.yml (AAP runs that step first).
# Root requirements.yml is left minimal so "ansible-galaxy install -r requirements.yml"
# does not parse version: master as LooseVersion (which fails on branch names).
roles: []
collections: []
