---
- hosts: localhost
  connection: local
  gather_facts: false

  # Define where to look for modules
  collections:
    - cust.overrides  # <--- Contains the Customer's 'fancy_echo'
    - osac.demo       # <--- Contains the Vendor's Role

  vars:
    # THE DYNAMIC POINTER
    # We explicitly tell the Role: "Don't use your tool. Use mine."
    provider_driver: "cust.overrides.fancy_echo_v1"

  tasks:
    - import_role:
        name: osac.demo.shadow_test