---
- name: Customer Deployment
  hosts: localhost
  connection: local
  gather_facts: false

  collections:
    - osac.demo

  tasks:
    - import_role:
        name: osac.demo.shadow_test
      vars:
        my_name: "Hijack Master"

        # THE POINTERS
        # 1. Role name in this project's roles/ (must match roles/override_driver/)
        fancy_echo_driver_role: "override_driver"

        # 2. Task file to load from that role's tasks/
        fancy_echo_driver_task: "override_driver.yml"