---
- name: Customer Deployment
  hosts: localhost
  connection: local
  gather_facts: false

  # We still need this to find the VENDOR role
  collections:
    - osac.demo

  tasks:
    - import_role:
        name: osac.demo.shadow_test
      vars:
        my_name: "Customer"