---
# Inherit flow from vendor; override step 1 (operate_v1) with our multiply role
- name: Customer deployment
  ansible.builtin.import_playbook: osac.demo.site
  vars:
    add_role_override:
      name: override_operate
      tasks_from: operate_v1.yml
