---
- name: Customer Deployment
  hosts: localhost
  connection: local
  gather_facts: false

  collections:
    - osac.demo

  tasks:
    - import_role:
        name: osac.demo.shadow_test
      vars:
        my_name: "Hijack Master"

        # THE POINTERS
        # 1. We tell the vendor to look for a role in the current project root
        #    (Using a dot '.' often signifies 'current project' or strict pathing)
        provider_driver_role: "." 

        # 2. We tell it which file to load
        provider_driver_task: "override_driver.yml"